### ISSUE TITLE
Two:  Typo & Function Clash

### ISSUE THREAD

**Issue by bentasm1** [Themekraft/BP-WC-Vendors#1]
1.) On BP Vendor Dashboard, "Coupongs" instead of "Coupons"

2.) The login redirect code is the same function name from our KB, so that errored out for me immediately when testing.  Might rename the function from login_redirect to something else. :)  Not a bug per say, just an oddity!

Thanks for writing this plugin, Sven!  It looks quite nice, and works very well.  I've created a forum post about it too:

https://www.wcvendors.com/help/topic/buddypress-wc-vendors-plugin-by-svenl77/

**Comment by svenl77** [comment]
Hi @bentasm1 

wow you are fast. I just have uploaded the plugin to wordpress.org and went to bed ;)

I have fixed all issues and release a new version. Will upload all to wordpress.org now.

Many thanks for your feedback!
