### ISSUE TITLE
BP profile breaks bad if WC Vendors PRO not active

### ISSUE THREAD

**Issue by originalfoo** [Themekraft/BP-WC-Vendors#2]
Steps to reproduce:
- Install & activate BP WC Vendors without first installing & activating WC Vendors Pro
- Go to your BP user profile page on front end
  - All the tabs and their content are missing

It would be nice if the BP WC Vendors plugin detected missing dependencies and displayed warning in backend and, ideally, didn't completely break the BP user profile on frontend.

Suggestion: Move the list of dependencies further up the [wordpress.org plugin page](https://wordpress.org/plugins/bp-wc-vendors/) to make them more obvious, and also hyperlink the plugins to avoid any possible confusion.

**Comment by svenl77** [comment]
Hi @aubergine10 thanks for your contribution should be fixed now.
